### ISSUE TITLE
Vertical menu should work more intuitive

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#1]
This theme is intended to use with the distro at http://github.com/vih/vih-build. Install the distro and enable the theme.

It is a theme converted to Radix / Bootstrap from another theme, which is used at http://vih.dk at the moment.

I wanted to keep using the same layout, but make it responsive. This works fairly well. However, a couple of things does not work, as I want it to.

On desktop: The sidebar menu should extend, when the parent is active, like it does on http://vih.dk/langekurser. I do not need the hover effect. I would prefer just to click on the link and it opens up exactly as it does on the current site.

On mobile, I still need the menu to work correctly, so it makes sense.

**Comment by shadcn** [comment]
I can see that this is already working. If a menu item has a child menu item, when the parent menu item is active, you can see it expanded. See screenshot below: 

![korte_kurser__sommerkurser_og_hojskole___site-install](https://cloud.githubusercontent.com/assets/124599/5162984/8023e038-73df-11e4-8c71-ae55bb0b7fc1.png)

**Comment by lsolesen** [comment]
The screenshot is not sport_2014, I think. It seems to be the old theme? Basically, what I want is to get sport_2014 to work in the same manner as the old theme (sport), but being responsive. Only thing is that the dropdowns should probably just be disabled, and the menu expanded when the parent is active. How is that possible?

**Comment by lsolesen** [comment]
I changed the production site to sport_2014 now.

**Comment by shadcn** [comment]
Ok. I'm still working on the chef to Radix 3.x upgrade.

On Tue, Nov 25, 2014 at 5:49 PM, Lars Olesen notifications@github.com
wrote:

> I changed the production site to sport_2014 now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vih/sport_2014/issues/1#issuecomment-64401625.

## 

Thanks
Arshad Chummun

**Comment by lsolesen** [comment]
@arshad Is @naughtydavid supposed to work on this issue also? Or will you have time to work on it soon.

**Comment by lsolesen** [comment]
Reassigning this to @mglaman as no work has taken place yet - and this is really important for our site.
