### ISSUE TITLE
Fix layout for different subpages

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#11]
Layout for stories severely broken

_stories_ vih.dk/nyheder

![skitch](https://cloud.githubusercontent.com/assets/148026/6313866/821c400c-b9c0-11e4-9409-b88d21eb346c.png)

_lectures_ vih.dk/foredrag

![skitch](https://cloud.githubusercontent.com/assets/148026/6313874/153b0102-b9c1-11e4-8939-33203de17cbd.png)

_short courses_ vih.dk/kortekurser

![skitch](https://cloud.githubusercontent.com/assets/148026/6313876/46ca9188-b9c1-11e4-8088-8dc4594aabe6.png)

**Comment by mglaman** [comment]
@lsolesen what's the end goal here for this to look like?

**Comment by lsolesen** [comment]
Pictures should have the same size!

**Comment by lsolesen** [comment]
This seems to be related to gh-4

**Comment by cornifex** [comment]
Commit above adds styling from #4 to the article teasers view. The image style will need to be changed from Panopoly Thumbnail to Panopoly Square to match the other pages

**Comment by cornifex** [comment]
Updated the live site to use panopoly square

**Comment by lsolesen** [comment]
@cornifex Did you also fix it in the code?
