### ISSUE TITLE
IE problems

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#12]
![attachment](https://cloud.githubusercontent.com/assets/148026/6331890/2ae544d2-bb82-11e4-86a9-d21fc9c0c2ee.png)

**Comment by lsolesen** [comment]
http://vih.dk/langekurser

**Comment by mglaman** [comment]
Note: Even with Bundler some weird things are happening when I compile the CSS... so I manually added fix for now in the .css, I don't trust my compiled version.
