### ISSUE TITLE
In mobile view clicking on the menu to minimize again not working

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#2]
I cannot remove the menu again when it appears on mobile.

**Comment by lsolesen** [comment]
@arshad Should @naugtydavid also work on this, or will you have time soon?

**Comment by shadcn** [comment]
Switching jQuery to 1.8 at /admin/config/development/jquery_update fixes this.

**Comment by lsolesen** [comment]
Confirmed. Any way to have Radix automatically set this?

**Comment by shadcn** [comment]
I'm working on a fix for Radix. Will tag a new release soon.

**Comment by lsolesen** [comment]
Panels IPE and the navigation (navbar module) breaks when updating to Jquery 1.8.
