### ISSUE TITLE
Short courses category pictures only fills half width on Ipad

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#3]
When in mobile mode on iPad (portrait) the category pictures on /kortekurser only fills up half of the viewport. They should fill up 100%.

**Comment by lsolesen** [comment]
Same is true for the teachers on the / and on /underviser and for /rejser.

**Comment by shadcn** [comment]
@lsolesen can you QA?

**Comment by lsolesen** [comment]
@arshad So I should add views_bootstrap to the stack and start using that instead. My worry is if I need to switch away from Bootstrap on my next theme, I need to alter all my views :/

**Comment by shadcn** [comment]
If you're using Bootstrap, views_bootstrap is highly recommended. 

(When you move away from Bootstrap, only the Bootstrap classes will be left in your views and you can always theme these.)
