### ISSUE TITLE
Media text should be vertically aligned

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#4]
The media components used for /kortekurser, /langekurser, /foredrag should have the text vertically aligned instead of aligned for the top.

**Comment by lsolesen** [comment]
This can be done with media-middle in Bootstrap 3. However, right now the pics are too small for this to look good.

**Comment by shadcn** [comment]
The commit above fixes this by making the thumbnail a bit bigger and vertically aligned the text. See screenshot below:

![lange_hojskolekurser___vejle_idraetshojskole](https://cloud.githubusercontent.com/assets/124599/5549233/b9cd2da4-8b9e-11e4-9b77-b5c456e31f4c.png)

**Comment by cornifex** [comment]
I've implemented @arshad 's fix on /kortekurser as well as /foredrag
